name: CI/CD Pipeline
env:
    FILE_NAME: "hello.py"
on: [push]
jobs:
    Job1:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the code
            uses: actions/checkout@v2
          - name: Run the script
            run:  python hello.py
    Job2:
        runs-on: ubuntu-latest
        needs: [Job1]
        steps:
          - name: Checkout the code
            uses: actions/checkout@v2
          - name: Create Artifact
            uses: actions/upload-artifact@v1.0.0
            with:
              name: artifact
              path: .